### YamlMime:ManagedReference
items:
- uid: WeAutoCommon.Configs.WeMettingConfig
  commentId: T:WeAutoCommon.Configs.WeMettingConfig
  id: WeMettingConfig
  parent: WeAutoCommon.Configs
  children:
  - WeAutoCommon.Configs.WeMettingConfig.#ctor
  langs:
  - csharp
  - vb
  name: WeMettingConfig
  nameWithType: WeMettingConfig
  fullName: WeAutoCommon.Configs.WeMettingConfig
  type: Class
  source:
    href: https://github.com/scottfly189/wxauto.net/blob/fd5d01c9759ea211906fca696a1dd38a53bd8438/WeAutoCommon/Configs/WeMettingConfig.cs
  assemblies:
  - WeAutoCommon
  namespace: WeAutoCommon.Configs
  summary: 腾迅会议配置类
  example: []
  syntax:
    content: public class WeMettingConfig
    content.vb: Public Class WeMettingConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  extensionMethods:
  - WeAutoCommon.Configs.WeMettingConfig.WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1
- uid: WeAutoCommon.Configs.WeMettingConfig.#ctor
  commentId: M:WeAutoCommon.Configs.WeMettingConfig.#ctor
  id: '#ctor'
  parent: WeAutoCommon.Configs.WeMettingConfig
  langs:
  - csharp
  - vb
  name: WeMettingConfig()
  nameWithType: WeMettingConfig.WeMettingConfig()
  fullName: WeAutoCommon.Configs.WeMettingConfig.WeMettingConfig()
  type: Constructor
  source:
    href: https://github.com/scottfly189/wxauto.net/blob/fd5d01c9759ea211906fca696a1dd38a53bd8438/WeAutoCommon/Configs/WeMettingConfig.cs
  assemblies:
  - WeAutoCommon
  namespace: WeAutoCommon.Configs
  syntax:
    content: public WeMettingConfig()
    content.vb: Public Sub New()
  overload: WeAutoCommon.Configs.WeMettingConfig.#ctor*
  nameWithType.vb: WeMettingConfig.New()
  fullName.vb: WeAutoCommon.Configs.WeMettingConfig.New()
  name.vb: New()
references:
- uid: WeAutoCommon.Configs
  commentId: N:WeAutoCommon.Configs
  isExternal: true
  href: WeAutoCommon.html
  name: WeAutoCommon.Configs
  nameWithType: WeAutoCommon.Configs
  fullName: WeAutoCommon.Configs
  spec.csharp:
  - uid: WeAutoCommon
    name: WeAutoCommon
    isExternal: true
    href: WeAutoCommon.html
  - name: .
  - uid: WeAutoCommon.Configs
    name: Configs
    isExternal: true
    href: WeAutoCommon.Configs.html
  spec.vb:
  - uid: WeAutoCommon
    name: WeAutoCommon
    isExternal: true
    href: WeAutoCommon.html
  - name: .
  - uid: WeAutoCommon.Configs
    name: Configs
    isExternal: true
    href: WeAutoCommon.Configs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: WeAutoCommon.Configs.WeMettingConfig.WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1
  commentId: M:WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1(``0)
  parent: WeAutoCommon.Models.FunctionalExtensions
  definition: WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1(``0)
  href: WeAutoCommon.Models.FunctionalExtensions.html#WeAutoCommon_Models_FunctionalExtensions_ToMaybe__1___0_
  name: ToMaybe<WeMettingConfig>(WeMettingConfig)
  nameWithType: FunctionalExtensions.ToMaybe<WeMettingConfig>(WeMettingConfig)
  fullName: WeAutoCommon.Models.FunctionalExtensions.ToMaybe<WeAutoCommon.Configs.WeMettingConfig>(WeAutoCommon.Configs.WeMettingConfig)
  nameWithType.vb: FunctionalExtensions.ToMaybe(Of WeMettingConfig)(WeMettingConfig)
  fullName.vb: WeAutoCommon.Models.FunctionalExtensions.ToMaybe(Of WeAutoCommon.Configs.WeMettingConfig)(WeAutoCommon.Configs.WeMettingConfig)
  name.vb: ToMaybe(Of WeMettingConfig)(WeMettingConfig)
  spec.csharp:
  - uid: WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1(WeAutoCommon.Configs.WeMettingConfig)
    name: ToMaybe
    isExternal: true
    href: WeAutoCommon.Models.FunctionalExtensions.html#WeAutoCommon_Models_FunctionalExtensions_ToMaybe__1___0_
  - name: <
  - uid: WeAutoCommon.Configs.WeMettingConfig
    name: WeMettingConfig
    isExternal: true
    href: WeAutoCommon.Configs.WeMettingConfig.html
  - name: '>'
  - name: (
  - uid: WeAutoCommon.Configs.WeMettingConfig
    name: WeMettingConfig
    isExternal: true
    href: WeAutoCommon.Configs.WeMettingConfig.html
  - name: )
  spec.vb:
  - uid: WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1(WeAutoCommon.Configs.WeMettingConfig)
    name: ToMaybe
    isExternal: true
    href: WeAutoCommon.Models.FunctionalExtensions.html#WeAutoCommon_Models_FunctionalExtensions_ToMaybe__1___0_
  - name: (
  - name: Of
  - name: " "
  - uid: WeAutoCommon.Configs.WeMettingConfig
    name: WeMettingConfig
    isExternal: true
    href: WeAutoCommon.Configs.WeMettingConfig.html
  - name: )
  - name: (
  - uid: WeAutoCommon.Configs.WeMettingConfig
    name: WeMettingConfig
    isExternal: true
    href: WeAutoCommon.Configs.WeMettingConfig.html
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1(``0)
  commentId: M:WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1(``0)
  isExternal: true
  href: WeAutoCommon.Models.FunctionalExtensions.html#WeAutoCommon_Models_FunctionalExtensions_ToMaybe__1___0_
  name: ToMaybe<T>(T)
  nameWithType: FunctionalExtensions.ToMaybe<T>(T)
  fullName: WeAutoCommon.Models.FunctionalExtensions.ToMaybe<T>(T)
  nameWithType.vb: FunctionalExtensions.ToMaybe(Of T)(T)
  fullName.vb: WeAutoCommon.Models.FunctionalExtensions.ToMaybe(Of T)(T)
  name.vb: ToMaybe(Of T)(T)
  spec.csharp:
  - uid: WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1(``0)
    name: ToMaybe
    isExternal: true
    href: WeAutoCommon.Models.FunctionalExtensions.html#WeAutoCommon_Models_FunctionalExtensions_ToMaybe__1___0_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: WeAutoCommon.Models.FunctionalExtensions.ToMaybe``1(``0)
    name: ToMaybe
    isExternal: true
    href: WeAutoCommon.Models.FunctionalExtensions.html#WeAutoCommon_Models_FunctionalExtensions_ToMaybe__1___0_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: WeAutoCommon.Models.FunctionalExtensions
  commentId: T:WeAutoCommon.Models.FunctionalExtensions
  parent: WeAutoCommon.Models
  isExternal: true
  href: WeAutoCommon.Models.FunctionalExtensions.html
  name: FunctionalExtensions
  nameWithType: FunctionalExtensions
  fullName: WeAutoCommon.Models.FunctionalExtensions
- uid: WeAutoCommon.Models
  commentId: N:WeAutoCommon.Models
  isExternal: true
  href: WeAutoCommon.html
  name: WeAutoCommon.Models
  nameWithType: WeAutoCommon.Models
  fullName: WeAutoCommon.Models
  spec.csharp:
  - uid: WeAutoCommon
    name: WeAutoCommon
    isExternal: true
    href: WeAutoCommon.html
  - name: .
  - uid: WeAutoCommon.Models
    name: Models
    isExternal: true
    href: WeAutoCommon.Models.html
  spec.vb:
  - uid: WeAutoCommon
    name: WeAutoCommon
    isExternal: true
    href: WeAutoCommon.html
  - name: .
  - uid: WeAutoCommon.Models
    name: Models
    isExternal: true
    href: WeAutoCommon.Models.html
- uid: WeAutoCommon.Configs.WeMettingConfig.#ctor*
  commentId: Overload:WeAutoCommon.Configs.WeMettingConfig.#ctor
  isExternal: true
  href: WeAutoCommon.Configs.WeMettingConfig.html#WeAutoCommon_Configs_WeMettingConfig__ctor
  name: WeMettingConfig
  nameWithType: WeMettingConfig.WeMettingConfig
  fullName: WeAutoCommon.Configs.WeMettingConfig.WeMettingConfig
  nameWithType.vb: WeMettingConfig.New
  fullName.vb: WeAutoCommon.Configs.WeMettingConfig.New
  name.vb: New
